### ISSUE TITLE
emits event in current tab

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/tab-emitter#17]
tab-emitter emits the event in every tab, including the sending tab. If possible, this should be an option.

Either way, this should be documented.

**Comment by Blaccexican** [comment]
#17

**Comment by Blaccexican** [comment]
#17

**Comment by Blaccexican** [comment]
#17

**Comment by Blaccexican** [comment]
#17
emits event in current tab
Opened by ArtskydJ 2 days ago

**Comment by ArtskydJ** [comment]
What?

**Comment by VarPDev** [comment]
Can you develop this in a few days?

**Comment by ArtskydJ** [comment]
documented now
